version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: ./src/Dockerfile
    container_name: app
    environment:
      - DB_URI=postgresql+psycopg2://myuser:123456789@host.docker.internal:5432/mydb

networks:
  default:
    driver: bridge
